import type { ImageProps } from "../utils/types";

export const images: ImageProps[] = [
  {
    id: 0,
    src: "https://images.unsplash.com/photo-1680007631114-cc0b37816fff?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80",
    href: "https://unsplash.com/photos/z-J6t9UJqEg",
    credits: "Maciek Sulkowski",
    reference: "https://unsplash.com/@imac666",
    location: "Pieniny, Poland",
    publishDate: "March 28, 2023",
    camera: "Canon EOS 5D Mark II",
    title: "A lone tree on top of a mountain at sunset",
    description: "Lorem ipsum odor amet, consectetuer adipiscing elit. Massa lacinia nisl ullamcorper nulla enim cubilia posuere. Nullam cursus ac ligula cubilia habitant nibh. Lacinia enim tortor sit nec molestie. Curabitur magna faucibus facilisi dictum ullamcorper felis volutpat eget!",
    width: 2070,
    height: 1380,
  },
  {
    id: 1,
    src: "https://images.unsplash.com/photo-1681648531827-e9d7591cf063?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80",
    href: "https://unsplash.com/photos/uWZL-6wsUt4",
    credits: "Nunzio Guerrera",
    reference: "https://unsplash.com/@nunzg",
    location: "Alberta, Canada",
    publishDate: "April 16, 2023",
    camera: "Nikon D800",
    title: "A mountain is reflected in a lake",
    description: "Lorem ipsum odor amet, consectetuer adipiscing elit. Massa lacinia nisl ullamcorper nulla enim cubilia posuere. Nullam cursus ac ligula cubilia habitant nibh. Lacinia enim tortor sit nec molestie. Curabitur magna faucibus facilisi dictum ullamcorper felis volutpat eget!",
    width: 2070,
    height: 1380,
  },
  {
    id: 2,
    src: "https://images.unsplash.com/photo-1681492955560-96937d474005?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80",
    href: "https://unsplash.com/photos/J1fuuj0fOPA",
    credits: "Nicolas Houdayer",
    reference: "https://unsplash.com/@ascalaphe",
    publishDate: "April 15, 2023",
    camera: "Fujifilm FinePix JX490",
    title: "A view of a body of water through a cave",
    description: "Lorem ipsum odor amet, consectetuer adipiscing elit. Massa lacinia nisl ullamcorper nulla enim cubilia posuere. Nullam cursus ac ligula cubilia habitant nibh. Lacinia enim tortor sit nec molestie. Curabitur magna faucibus facilisi dictum ullamcorper felis volutpat eget!",
    width: 2070,
    height: 1380,
  },
  {
    id: 3,
    src: "https://images.unsplash.com/photo-1681927269046-1263e3282bb8?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80",
    href: "https://unsplash.com/photos/UESGgdEAHvE",
    credits: "Mason Field",
    reference: "https://unsplash.com/@masonrfield",
    location: "Point Reyes Station, CA, USA",
    publishDate: "April 20, 2023",
    camera: "Sony ILCE-7RM2",
    title: "A couple of animals that are standing in the grass",
    description: "Lorem ipsum odor amet, consectetuer adipiscing elit. Massa lacinia nisl ullamcorper nulla enim cubilia posuere. Nullam cursus ac ligula cubilia habitant nibh. Lacinia enim tortor sit nec molestie. Curabitur magna faucibus facilisi dictum ullamcorper felis volutpat eget!",
    width: 2070,
    height: 1380,
  },
  {
    id: 4,
    src: "https://images.unsplash.com/photo-1680759426107-fde98c896b9f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80",
    href: "https://unsplash.com/photos/MJx68dqaIA4",
    credits: "Tingfeng Xia",
    reference: "https://unsplash.com/@tfx",
    location: "Zabriskie Point, California, USA",
    publishDate: "April 6, 2023",
    camera: "Fujifilm, X-T4",
    title: "A view of a mountain range in the desert",
    description: "Lorem ipsum odor amet, consectetuer adipiscing elit. Massa lacinia nisl ullamcorper nulla enim cubilia posuere. Nullam cursus ac ligula cubilia habitant nibh. Lacinia enim tortor sit nec molestie. Curabitur magna faucibus facilisi dictum ullamcorper felis volutpat eget!",
    width: 2070,
    height: 1380,
  },
  {
    id: 5,
    src: "https://images.unsplash.com/photo-1682001426601-c7fdc9ea5b4e?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80",
    href: "https://unsplash.com/photos/kvZ8m7KaL-w",
    credits: "Marcus Ganahl",
    reference: "https://unsplash.com/@marcus_ganahl",
    location: "Lago di Braies, Prags, Autonome Provinz Bozen   Südtirol, Italien",
    publishDate: "April 20, 2023",
    camera: "Fujifilm X-T3",
    title: "Morning at the mountain lake in South Tyrol",
    description: "Lorem ipsum odor amet, consectetuer adipiscing elit. Massa lacinia nisl ullamcorper nulla enim cubilia posuere. Nullam cursus ac ligula cubilia habitant nibh. Lacinia enim tortor sit nec molestie. Curabitur magna faucibus facilisi dictum ullamcorper felis volutpat eget!",
    width: 2070,
    height: 1380,
  },
  {
    id: 6,
    src: "https://images.unsplash.com/photo-1681276974957-890cf1dcba67?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80",
    href: "https://unsplash.com/photos/G_z1TWdt1RM",
    credits: "Zetong Li",
    reference: "https://unsplash.com/@zetong",
    location: "California, USA",
    publishDate: "April 12, 2023",
    camera: "Nikon Z 6",
    title: "A group of sand dunes with mountains in the background",
    description: "Lorem ipsum odor amet, consectetuer adipiscing elit. Massa lacinia nisl ullamcorper nulla enim cubilia posuere. Nullam cursus ac ligula cubilia habitant nibh. Lacinia enim tortor sit nec molestie. Curabitur magna faucibus facilisi dictum ullamcorper felis volutpat eget!",
    width: 2070,
    height: 1380,
  },
  {
    id: 7,
    src: "https://images.unsplash.com/photo-1680950781367-fe720fae1e4e?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80",
    href: "https://unsplash.com/photos/7v21HagZvzE",
    credits: "Marko Brečić",
    reference: "https://unsplash.com/@markobrecic",
    location: "Aarhus, Denmark",
    publishDate: "April 8, 2023",
    camera: "Fujifilm X-T20",
    title: "A bunch of purple flowers that are on a wall",
    description: "Lorem ipsum odor amet, consectetuer adipiscing elit. Massa lacinia nisl ullamcorper nulla enim cubilia posuere. Nullam cursus ac ligula cubilia habitant nibh. Lacinia enim tortor sit nec molestie. Curabitur magna faucibus facilisi dictum ullamcorper felis volutpat eget!",
    width: 2070,
    height: 1380,
  },
  {
    id: 8,
    src: "https://images.unsplash.com/photo-1681953447398-d5193e0b024c?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80",
    href: "https://unsplash.com/photos/hbUijwwvFfo",
    credits: "Valeriia Neganova",
    reference: "https://unsplash.com/@neganova",
    location: "Florida, USA",
    publishDate: "April 20, 2023",
    camera: "Hasselblad, L1D-20c",
    title: "A bird's eye view of a body of water",
    description: "Lorem ipsum odor amet, consectetuer adipiscing elit. Massa lacinia nisl ullamcorper nulla enim cubilia posuere. Nullam cursus ac ligula cubilia habitant nibh. Lacinia enim tortor sit nec molestie. Curabitur magna faucibus facilisi dictum ullamcorper felis volutpat eget!",
    width: 2070,
    height: 1380,
  },
  {
    id: 9,
    src: "https://images.unsplash.com/photo-1681130497030-2e2ff8bb552c?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80",
    href: "https://unsplash.com/photos/nH_iaTy3N-M",
    credits: "Bryan Dijkhuizen",
    reference: "https://unsplash.com/@bryandijkh",
    location: "Lugano, Switzerland",
    publishDate: "April 10, 2023",
    camera: "Canon EOS M50m2",
    title: "A dock with a mountain in the background",
    description: "Lorem ipsum odor amet, consectetuer adipiscing elit. Massa lacinia nisl ullamcorper nulla enim cubilia posuere. Nullam cursus ac ligula cubilia habitant nibh. Lacinia enim tortor sit nec molestie. Curabitur magna faucibus facilisi dictum ullamcorper felis volutpat eget!",
    width: 2070,
    height: 1380,
  },
  {
    id: 10,
    src: "https://images.unsplash.com/photo-1680980310413-ecfbc4639771?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80",
    href: "https://unsplash.com/photos/OprsVyOCLNg",
    credits: "Sergei Chyrkov",
    reference: "https://unsplash.com/@chyrkov",
    location: "Antalya, Türkiye",
    publishDate: "April 9, 2023",
    camera: "Fujifilm X100V",
    title: "View at Konyaaltı Beach in Antalya",
    description: "Lorem ipsum odor amet, consectetuer adipiscing elit. Massa lacinia nisl ullamcorper nulla enim cubilia posuere. Nullam cursus ac ligula cubilia habitant nibh. Lacinia enim tortor sit nec molestie. Curabitur magna faucibus facilisi dictum ullamcorper felis volutpat eget!",
    width: 2070,
    height: 1380,
  },
  {
    id: 11,
    src: "https://images.unsplash.com/photo-1679224871886-2e67940f937d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80",
    href: "https://unsplash.com/photos/EylXr_kvBFU",
    credits: "Chanwei",
    reference: "https://unsplash.com/@chanwei_snap",
    location: "Chureito Pagoda, 2 chome 4 1 Asama, Fujiyoshida, Yamanashi, Japan",
    publishDate: "March 19, 2023",
    title: "A tall pagoda with a mountain in the background",
    description: "Lorem ipsum odor amet, consectetuer adipiscing elit. Massa lacinia nisl ullamcorper nulla enim cubilia posuere. Nullam cursus ac ligula cubilia habitant nibh. Lacinia enim tortor sit nec molestie. Curabitur magna faucibus facilisi dictum ullamcorper felis volutpat eget!",
    width: 2070,
    height: 1380,
  },
];